/*
 * This file is generated by jOOQ.
 */
package ca.bc.gov.educ.api.sld.jooq.tables;


import ca.bc.gov.educ.api.sld.jooq.DefaultSchema;
import ca.bc.gov.educ.api.sld.jooq.Keys;
import ca.bc.gov.educ.api.sld.jooq.tables.records.StudentHistoryVwRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row16;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentHistoryVw extends TableImpl<StudentHistoryVwRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>STUDENT_HISTORY_VW</code>
     */
    public static final StudentHistoryVw STUDENT_HISTORY_VW = new StudentHistoryVw();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StudentHistoryVwRecord> getRecordType() {
        return StudentHistoryVwRecord.class;
    }

    /**
     * The column <code>STUDENT_HISTORY_VW.VLOCAL_STUDENT_ID</code>.
     */
    public final TableField<StudentHistoryVwRecord, String> VLOCAL_STUDENT_ID = createField(DSL.name("VLOCAL_STUDENT_ID"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>STUDENT_HISTORY_VW.VREPORT_DATE</code>.
     */
    public final TableField<StudentHistoryVwRecord, Long> VREPORT_DATE = createField(DSL.name("VREPORT_DATE"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>STUDENT_HISTORY_VW.VBIRTH_DATE</code>.
     */
    public final TableField<StudentHistoryVwRecord, String> VBIRTH_DATE = createField(DSL.name("VBIRTH_DATE"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>STUDENT_HISTORY_VW.VDISTNO</code>.
     */
    public final TableField<StudentHistoryVwRecord, String> VDISTNO = createField(DSL.name("VDISTNO"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>STUDENT_HISTORY_VW.VENROLLED_GRADE_CODE</code>.
     */
    public final TableField<StudentHistoryVwRecord, String> VENROLLED_GRADE_CODE = createField(DSL.name("VENROLLED_GRADE_CODE"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>STUDENT_HISTORY_VW.VLEGAL_GIVEN_NAME</code>.
     */
    public final TableField<StudentHistoryVwRecord, String> VLEGAL_GIVEN_NAME = createField(DSL.name("VLEGAL_GIVEN_NAME"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>STUDENT_HISTORY_VW.VLEGAL_MIDDLE_NAME</code>.
     */
    public final TableField<StudentHistoryVwRecord, String> VLEGAL_MIDDLE_NAME = createField(DSL.name("VLEGAL_MIDDLE_NAME"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>STUDENT_HISTORY_VW.VLEGAL_SURNAME</code>.
     */
    public final TableField<StudentHistoryVwRecord, String> VLEGAL_SURNAME = createField(DSL.name("VLEGAL_SURNAME"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>STUDENT_HISTORY_VW.VPEN</code>.
     */
    public final TableField<StudentHistoryVwRecord, String> VPEN = createField(DSL.name("VPEN"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>STUDENT_HISTORY_VW.VPOSTAL</code>.
     */
    public final TableField<StudentHistoryVwRecord, String> VPOSTAL = createField(DSL.name("VPOSTAL"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>STUDENT_HISTORY_VW.VSCHLNO</code>.
     */
    public final TableField<StudentHistoryVwRecord, String> VSCHLNO = createField(DSL.name("VSCHLNO"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>STUDENT_HISTORY_VW.VSEX</code>.
     */
    public final TableField<StudentHistoryVwRecord, String> VSEX = createField(DSL.name("VSEX"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>STUDENT_HISTORY_VW.VSOURCE</code>.
     */
    public final TableField<StudentHistoryVwRecord, String> VSOURCE = createField(DSL.name("VSOURCE"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>STUDENT_HISTORY_VW.VUSUAL_GIVEN_NAME</code>.
     */
    public final TableField<StudentHistoryVwRecord, String> VUSUAL_GIVEN_NAME = createField(DSL.name("VUSUAL_GIVEN_NAME"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>STUDENT_HISTORY_VW.VUSUAL_MIDDLE_NAME</code>.
     */
    public final TableField<StudentHistoryVwRecord, String> VUSUAL_MIDDLE_NAME = createField(DSL.name("VUSUAL_MIDDLE_NAME"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>STUDENT_HISTORY_VW.VUSUAL_SURNAME</code>.
     */
    public final TableField<StudentHistoryVwRecord, String> VUSUAL_SURNAME = createField(DSL.name("VUSUAL_SURNAME"), SQLDataType.VARCHAR(255), this, "");

    private StudentHistoryVw(Name alias, Table<StudentHistoryVwRecord> aliased) {
        this(alias, aliased, null);
    }

    private StudentHistoryVw(Name alias, Table<StudentHistoryVwRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>STUDENT_HISTORY_VW</code> table reference
     */
    public StudentHistoryVw(String alias) {
        this(DSL.name(alias), STUDENT_HISTORY_VW);
    }

    /**
     * Create an aliased <code>STUDENT_HISTORY_VW</code> table reference
     */
    public StudentHistoryVw(Name alias) {
        this(alias, STUDENT_HISTORY_VW);
    }

    /**
     * Create a <code>STUDENT_HISTORY_VW</code> table reference
     */
    public StudentHistoryVw() {
        this(DSL.name("STUDENT_HISTORY_VW"), null);
    }

    public <O extends Record> StudentHistoryVw(Table<O> child, ForeignKey<O, StudentHistoryVwRecord> key) {
        super(child, key, STUDENT_HISTORY_VW);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<StudentHistoryVwRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_D;
    }

    @Override
    public List<UniqueKey<StudentHistoryVwRecord>> getKeys() {
        return Arrays.<UniqueKey<StudentHistoryVwRecord>>asList(Keys.CONSTRAINT_D);
    }

    @Override
    public StudentHistoryVw as(String alias) {
        return new StudentHistoryVw(DSL.name(alias), this);
    }

    @Override
    public StudentHistoryVw as(Name alias) {
        return new StudentHistoryVw(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public StudentHistoryVw rename(String name) {
        return new StudentHistoryVw(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StudentHistoryVw rename(Name name) {
        return new StudentHistoryVw(name, null);
    }

    // -------------------------------------------------------------------------
    // Row16 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row16<String, Long, String, String, String, String, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row16) super.fieldsRow();
    }
}
