/*
 * This file is generated by jOOQ.
 */
package ca.bc.gov.educ.api.sld.jooq;


import ca.bc.gov.educ.api.sld.jooq.tables.DiaStudent;
import ca.bc.gov.educ.api.sld.jooq.tables.Student;
import ca.bc.gov.educ.api.sld.jooq.tables.StudentHistoryVw;
import ca.bc.gov.educ.api.sld.jooq.tables.StudentPrograms;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>DIA_STUDENT</code>.
     */
    public final DiaStudent DIA_STUDENT = DiaStudent.DIA_STUDENT;

    /**
     * The table <code>STUDENT</code>.
     */
    public final Student STUDENT = Student.STUDENT;

    /**
     * The table <code>STUDENT_HISTORY_VW</code>.
     */
    public final StudentHistoryVw STUDENT_HISTORY_VW = StudentHistoryVw.STUDENT_HISTORY_VW;

    /**
     * The table <code>STUDENT_PROGRAMS</code>.
     */
    public final StudentPrograms STUDENT_PROGRAMS = StudentPrograms.STUDENT_PROGRAMS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            DiaStudent.DIA_STUDENT,
            Student.STUDENT,
            StudentHistoryVw.STUDENT_HISTORY_VW,
            StudentPrograms.STUDENT_PROGRAMS);
    }
}
