/*
 * This file is generated by jOOQ.
 */
package ca.bc.gov.educ.api.sld.jooq;


import ca.bc.gov.educ.api.sld.jooq.tables.DiaStudent;
import ca.bc.gov.educ.api.sld.jooq.tables.Student;
import ca.bc.gov.educ.api.sld.jooq.tables.StudentHistoryVw;
import ca.bc.gov.educ.api.sld.jooq.tables.StudentPrograms;
import ca.bc.gov.educ.api.sld.jooq.tables.records.DiaStudentRecord;
import ca.bc.gov.educ.api.sld.jooq.tables.records.StudentHistoryVwRecord;
import ca.bc.gov.educ.api.sld.jooq.tables.records.StudentProgramsRecord;
import ca.bc.gov.educ.api.sld.jooq.tables.records.StudentRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DiaStudentRecord> CONSTRAINT_2 = Internal.createUniqueKey(DiaStudent.DIA_STUDENT, DSL.name("CONSTRAINT_2"), new TableField[] { DiaStudent.DIA_STUDENT.PEN, DiaStudent.DIA_STUDENT.REPORT_DATE }, true);
    public static final UniqueKey<StudentRecord> CONSTRAINT_B = Internal.createUniqueKey(Student.STUDENT, DSL.name("CONSTRAINT_B"), new TableField[] { Student.STUDENT.REPORT_DATE, Student.STUDENT.STUDENT_ID }, true);
    public static final UniqueKey<StudentHistoryVwRecord> CONSTRAINT_D = Internal.createUniqueKey(StudentHistoryVw.STUDENT_HISTORY_VW, DSL.name("CONSTRAINT_D"), new TableField[] { StudentHistoryVw.STUDENT_HISTORY_VW.VLOCAL_STUDENT_ID, StudentHistoryVw.STUDENT_HISTORY_VW.VREPORT_DATE }, true);
    public static final UniqueKey<StudentProgramsRecord> CONSTRAINT_8 = Internal.createUniqueKey(StudentPrograms.STUDENT_PROGRAMS, DSL.name("CONSTRAINT_8"), new TableField[] { StudentPrograms.STUDENT_PROGRAMS.REPORT_DATE, StudentPrograms.STUDENT_PROGRAMS.STUDENT_ID }, true);
}
