/*
 * This file is generated by jOOQ.
 */
package ca.bc.gov.educ.api.sld.jooq;


import ca.bc.gov.educ.api.sld.jooq.tables.DiaStudent;
import ca.bc.gov.educ.api.sld.jooq.tables.Student;
import ca.bc.gov.educ.api.sld.jooq.tables.StudentHistoryVw;
import ca.bc.gov.educ.api.sld.jooq.tables.StudentPrograms;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>DIA_STUDENT</code>.
     */
    public static final DiaStudent DIA_STUDENT = DiaStudent.DIA_STUDENT;

    /**
     * The table <code>STUDENT</code>.
     */
    public static final Student STUDENT = Student.STUDENT;

    /**
     * The table <code>STUDENT_HISTORY_VW</code>.
     */
    public static final StudentHistoryVw STUDENT_HISTORY_VW = StudentHistoryVw.STUDENT_HISTORY_VW;

    /**
     * The table <code>STUDENT_PROGRAMS</code>.
     */
    public static final StudentPrograms STUDENT_PROGRAMS = StudentPrograms.STUDENT_PROGRAMS;
}
