/*
 * This file is generated by jOOQ.
 */
package ca.bc.gov.educ.api.sld.jooq.tables.records;


import ca.bc.gov.educ.api.sld.jooq.tables.DiaStudent;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DiaStudentRecord extends UpdatableRecordImpl<DiaStudentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>DIA_STUDENT.PEN</code>.
     */
    public void setPen(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.PEN</code>.
     */
    public String getPen() {
        return (String) get(0);
    }

    /**
     * Setter for <code>DIA_STUDENT.REPORT_DATE</code>.
     */
    public void setReportDate(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.REPORT_DATE</code>.
     */
    public Long getReportDate() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>DIA_STUDENT.AGREEMENT_TYPE</code>.
     */
    public void setAgreementType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.AGREEMENT_TYPE</code>.
     */
    public String getAgreementType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>DIA_STUDENT.BAND_CODE</code>.
     */
    public void setBandCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.BAND_CODE</code>.
     */
    public String getBandCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>DIA_STUDENT.BANDNAME</code>.
     */
    public void setBandname(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.BANDNAME</code>.
     */
    public String getBandname() {
        return (String) get(4);
    }

    /**
     * Setter for <code>DIA_STUDENT.BANDRESNUM</code>.
     */
    public void setBandresnum(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.BANDRESNUM</code>.
     */
    public String getBandresnum() {
        return (String) get(5);
    }

    /**
     * Setter for <code>DIA_STUDENT.COMMENT</code>.
     */
    public void setComment(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.COMMENT</code>.
     */
    public String getComment() {
        return (String) get(6);
    }

    /**
     * Setter for <code>DIA_STUDENT.DIA_SCHOOL_INFO_WRONG</code>.
     */
    public void setDiaSchoolInfoWrong(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.DIA_SCHOOL_INFO_WRONG</code>.
     */
    public String getDiaSchoolInfoWrong() {
        return (String) get(7);
    }

    /**
     * Setter for <code>DIA_STUDENT.DISTNO</code>.
     */
    public void setDistno(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.DISTNO</code>.
     */
    public String getDistno() {
        return (String) get(8);
    }

    /**
     * Setter for <code>DIA_STUDENT.DISTNO_NEW</code>.
     */
    public void setDistnoNew(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.DISTNO_NEW</code>.
     */
    public String getDistnoNew() {
        return (String) get(9);
    }

    /**
     * Setter for <code>DIA_STUDENT.FRBANDNUM</code>.
     */
    public void setFrbandnum(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.FRBANDNUM</code>.
     */
    public String getFrbandnum() {
        return (String) get(10);
    }

    /**
     * Setter for <code>DIA_STUDENT.FTE_VAL</code>.
     */
    public void setFteVal(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.FTE_VAL</code>.
     */
    public Long getFteVal() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>DIA_STUDENT.ORIG_PEN</code>.
     */
    public void setOrigPen(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.ORIG_PEN</code>.
     */
    public String getOrigPen() {
        return (String) get(12);
    }

    /**
     * Setter for <code>DIA_STUDENT.PEN_COMMENT</code>.
     */
    public void setPenComment(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.PEN_COMMENT</code>.
     */
    public String getPenComment() {
        return (String) get(13);
    }

    /**
     * Setter for <code>DIA_STUDENT.PEN_STATUS</code>.
     */
    public void setPenStatus(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.PEN_STATUS</code>.
     */
    public String getPenStatus() {
        return (String) get(14);
    }

    /**
     * Setter for <code>DIA_STUDENT.POSTED_PEN</code>.
     */
    public void setPostedPen(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.POSTED_PEN</code>.
     */
    public String getPostedPen() {
        return (String) get(15);
    }

    /**
     * Setter for <code>DIA_STUDENT.RECORD_NUMBER</code>.
     */
    public void setRecordNumber(Long value) {
        set(16, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.RECORD_NUMBER</code>.
     */
    public Long getRecordNumber() {
        return (Long) get(16);
    }

    /**
     * Setter for <code>DIA_STUDENT.SCHBOARD</code>.
     */
    public void setSchboard(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.SCHBOARD</code>.
     */
    public String getSchboard() {
        return (String) get(17);
    }

    /**
     * Setter for <code>DIA_STUDENT.SCHLNO</code>.
     */
    public void setSchlno(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.SCHLNO</code>.
     */
    public String getSchlno() {
        return (String) get(18);
    }

    /**
     * Setter for <code>DIA_STUDENT.SCHLNO_NEW</code>.
     */
    public void setSchlnoNew(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.SCHLNO_NEW</code>.
     */
    public String getSchlnoNew() {
        return (String) get(19);
    }

    /**
     * Setter for <code>DIA_STUDENT.SCHNUM</code>.
     */
    public void setSchnum(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.SCHNUM</code>.
     */
    public String getSchnum() {
        return (String) get(20);
    }

    /**
     * Setter for <code>DIA_STUDENT.SCHOOL_NAME</code>.
     */
    public void setSchoolName(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.SCHOOL_NAME</code>.
     */
    public String getSchoolName() {
        return (String) get(21);
    }

    /**
     * Setter for <code>DIA_STUDENT.SCHTYPE</code>.
     */
    public void setSchtype(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.SCHTYPE</code>.
     */
    public String getSchtype() {
        return (String) get(22);
    }

    /**
     * Setter for <code>DIA_STUDENT.SITENO</code>.
     */
    public void setSiteno(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.SITENO</code>.
     */
    public String getSiteno() {
        return (String) get(23);
    }

    /**
     * Setter for <code>DIA_STUDENT.SITENO_NEW</code>.
     */
    public void setSitenoNew(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.SITENO_NEW</code>.
     */
    public String getSitenoNew() {
        return (String) get(24);
    }

    /**
     * Setter for <code>DIA_STUDENT.STUD_BIRTH</code>.
     */
    public void setStudBirth(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.STUD_BIRTH</code>.
     */
    public String getStudBirth() {
        return (String) get(25);
    }

    /**
     * Setter for <code>DIA_STUDENT.STUD_GIVEN</code>.
     */
    public void setStudGiven(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.STUD_GIVEN</code>.
     */
    public String getStudGiven() {
        return (String) get(26);
    }

    /**
     * Setter for <code>DIA_STUDENT.STUD_GRADE</code>.
     */
    public void setStudGrade(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.STUD_GRADE</code>.
     */
    public String getStudGrade() {
        return (String) get(27);
    }

    /**
     * Setter for <code>DIA_STUDENT.STUD_MIDDLE</code>.
     */
    public void setStudMiddle(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.STUD_MIDDLE</code>.
     */
    public String getStudMiddle() {
        return (String) get(28);
    }

    /**
     * Setter for <code>DIA_STUDENT.STUD_NEW_FLAG</code>.
     */
    public void setStudNewFlag(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.STUD_NEW_FLAG</code>.
     */
    public String getStudNewFlag() {
        return (String) get(29);
    }

    /**
     * Setter for <code>DIA_STUDENT.STUD_SEX</code>.
     */
    public void setStudSex(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.STUD_SEX</code>.
     */
    public String getStudSex() {
        return (String) get(30);
    }

    /**
     * Setter for <code>DIA_STUDENT.STUD_SURNAME</code>.
     */
    public void setStudSurname(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.STUD_SURNAME</code>.
     */
    public String getStudSurname() {
        return (String) get(31);
    }

    /**
     * Setter for <code>DIA_STUDENT.USUAL_GIVEN</code>.
     */
    public void setUsualGiven(String value) {
        set(32, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.USUAL_GIVEN</code>.
     */
    public String getUsualGiven() {
        return (String) get(32);
    }

    /**
     * Setter for <code>DIA_STUDENT.USUAL_SURNAME</code>.
     */
    public void setUsualSurname(String value) {
        set(33, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.USUAL_SURNAME</code>.
     */
    public String getUsualSurname() {
        return (String) get(33);
    }

    /**
     * Setter for <code>DIA_STUDENT.WITHDRAWAL_CODE</code>.
     */
    public void setWithdrawalCode(String value) {
        set(34, value);
    }

    /**
     * Getter for <code>DIA_STUDENT.WITHDRAWAL_CODE</code>.
     */
    public String getWithdrawalCode() {
        return (String) get(34);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DiaStudentRecord
     */
    public DiaStudentRecord() {
        super(DiaStudent.DIA_STUDENT);
    }

    /**
     * Create a detached, initialised DiaStudentRecord
     */
    public DiaStudentRecord(String pen, Long reportDate, String agreementType, String bandCode, String bandname, String bandresnum, String comment, String diaSchoolInfoWrong, String distno, String distnoNew, String frbandnum, Long fteVal, String origPen, String penComment, String penStatus, String postedPen, Long recordNumber, String schboard, String schlno, String schlnoNew, String schnum, String schoolName, String schtype, String siteno, String sitenoNew, String studBirth, String studGiven, String studGrade, String studMiddle, String studNewFlag, String studSex, String studSurname, String usualGiven, String usualSurname, String withdrawalCode) {
        super(DiaStudent.DIA_STUDENT);

        setPen(pen);
        setReportDate(reportDate);
        setAgreementType(agreementType);
        setBandCode(bandCode);
        setBandname(bandname);
        setBandresnum(bandresnum);
        setComment(comment);
        setDiaSchoolInfoWrong(diaSchoolInfoWrong);
        setDistno(distno);
        setDistnoNew(distnoNew);
        setFrbandnum(frbandnum);
        setFteVal(fteVal);
        setOrigPen(origPen);
        setPenComment(penComment);
        setPenStatus(penStatus);
        setPostedPen(postedPen);
        setRecordNumber(recordNumber);
        setSchboard(schboard);
        setSchlno(schlno);
        setSchlnoNew(schlnoNew);
        setSchnum(schnum);
        setSchoolName(schoolName);
        setSchtype(schtype);
        setSiteno(siteno);
        setSitenoNew(sitenoNew);
        setStudBirth(studBirth);
        setStudGiven(studGiven);
        setStudGrade(studGrade);
        setStudMiddle(studMiddle);
        setStudNewFlag(studNewFlag);
        setStudSex(studSex);
        setStudSurname(studSurname);
        setUsualGiven(usualGiven);
        setUsualSurname(usualSurname);
        setWithdrawalCode(withdrawalCode);
    }
}
