/*
 * This file is generated by jOOQ.
 */
package ca.bc.gov.educ.api.sld.jooq.tables.records;


import ca.bc.gov.educ.api.sld.jooq.tables.StudentPrograms;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentProgramsRecord extends UpdatableRecordImpl<StudentProgramsRecord> implements Record7<Long, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>STUDENT_PROGRAMS.REPORT_DATE</code>.
     */
    public void setReportDate(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>STUDENT_PROGRAMS.REPORT_DATE</code>.
     */
    public Long getReportDate() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>STUDENT_PROGRAMS.STUDENT_ID</code>.
     */
    public void setStudentId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>STUDENT_PROGRAMS.STUDENT_ID</code>.
     */
    public String getStudentId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>STUDENT_PROGRAMS.CAREER_PROGRAM</code>.
     */
    public void setCareerProgram(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>STUDENT_PROGRAMS.CAREER_PROGRAM</code>.
     */
    public String getCareerProgram() {
        return (String) get(2);
    }

    /**
     * Setter for <code>STUDENT_PROGRAMS.DISTNO</code>.
     */
    public void setDistno(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>STUDENT_PROGRAMS.DISTNO</code>.
     */
    public String getDistno() {
        return (String) get(3);
    }

    /**
     * Setter for <code>STUDENT_PROGRAMS.ENROLLED_PROGRAM_CODE</code>.
     */
    public void setEnrolledProgramCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>STUDENT_PROGRAMS.ENROLLED_PROGRAM_CODE</code>.
     */
    public String getEnrolledProgramCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>STUDENT_PROGRAMS.PEN</code>.
     */
    public void setPen(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>STUDENT_PROGRAMS.PEN</code>.
     */
    public String getPen() {
        return (String) get(5);
    }

    /**
     * Setter for <code>STUDENT_PROGRAMS.SCHLNO</code>.
     */
    public void setSchlno(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>STUDENT_PROGRAMS.SCHLNO</code>.
     */
    public String getSchlno() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, String, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, String, String, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return StudentPrograms.STUDENT_PROGRAMS.REPORT_DATE;
    }

    @Override
    public Field<String> field2() {
        return StudentPrograms.STUDENT_PROGRAMS.STUDENT_ID;
    }

    @Override
    public Field<String> field3() {
        return StudentPrograms.STUDENT_PROGRAMS.CAREER_PROGRAM;
    }

    @Override
    public Field<String> field4() {
        return StudentPrograms.STUDENT_PROGRAMS.DISTNO;
    }

    @Override
    public Field<String> field5() {
        return StudentPrograms.STUDENT_PROGRAMS.ENROLLED_PROGRAM_CODE;
    }

    @Override
    public Field<String> field6() {
        return StudentPrograms.STUDENT_PROGRAMS.PEN;
    }

    @Override
    public Field<String> field7() {
        return StudentPrograms.STUDENT_PROGRAMS.SCHLNO;
    }

    @Override
    public Long component1() {
        return getReportDate();
    }

    @Override
    public String component2() {
        return getStudentId();
    }

    @Override
    public String component3() {
        return getCareerProgram();
    }

    @Override
    public String component4() {
        return getDistno();
    }

    @Override
    public String component5() {
        return getEnrolledProgramCode();
    }

    @Override
    public String component6() {
        return getPen();
    }

    @Override
    public String component7() {
        return getSchlno();
    }

    @Override
    public Long value1() {
        return getReportDate();
    }

    @Override
    public String value2() {
        return getStudentId();
    }

    @Override
    public String value3() {
        return getCareerProgram();
    }

    @Override
    public String value4() {
        return getDistno();
    }

    @Override
    public String value5() {
        return getEnrolledProgramCode();
    }

    @Override
    public String value6() {
        return getPen();
    }

    @Override
    public String value7() {
        return getSchlno();
    }

    @Override
    public StudentProgramsRecord value1(Long value) {
        setReportDate(value);
        return this;
    }

    @Override
    public StudentProgramsRecord value2(String value) {
        setStudentId(value);
        return this;
    }

    @Override
    public StudentProgramsRecord value3(String value) {
        setCareerProgram(value);
        return this;
    }

    @Override
    public StudentProgramsRecord value4(String value) {
        setDistno(value);
        return this;
    }

    @Override
    public StudentProgramsRecord value5(String value) {
        setEnrolledProgramCode(value);
        return this;
    }

    @Override
    public StudentProgramsRecord value6(String value) {
        setPen(value);
        return this;
    }

    @Override
    public StudentProgramsRecord value7(String value) {
        setSchlno(value);
        return this;
    }

    @Override
    public StudentProgramsRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StudentProgramsRecord
     */
    public StudentProgramsRecord() {
        super(StudentPrograms.STUDENT_PROGRAMS);
    }

    /**
     * Create a detached, initialised StudentProgramsRecord
     */
    public StudentProgramsRecord(Long reportDate, String studentId, String careerProgram, String distno, String enrolledProgramCode, String pen, String schlno) {
        super(StudentPrograms.STUDENT_PROGRAMS);

        setReportDate(reportDate);
        setStudentId(studentId);
        setCareerProgram(careerProgram);
        setDistno(distno);
        setEnrolledProgramCode(enrolledProgramCode);
        setPen(pen);
        setSchlno(schlno);
    }
}
