/*
 * This file is generated by jOOQ.
 */
package ca.bc.gov.educ.api.sld.jooq.tables.records;


import ca.bc.gov.educ.api.sld.jooq.tables.StudentHistoryVw;

import org.jooq.Field;
import org.jooq.Record16;
import org.jooq.Record2;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentHistoryVwRecord extends UpdatableRecordImpl<StudentHistoryVwRecord> implements Record16<String, Long, String, String, String, String, String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>STUDENT_HISTORY_VW.VLOCAL_STUDENT_ID</code>.
     */
    public void setVlocalStudentId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>STUDENT_HISTORY_VW.VLOCAL_STUDENT_ID</code>.
     */
    public String getVlocalStudentId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>STUDENT_HISTORY_VW.VREPORT_DATE</code>.
     */
    public void setVreportDate(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>STUDENT_HISTORY_VW.VREPORT_DATE</code>.
     */
    public Long getVreportDate() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>STUDENT_HISTORY_VW.VBIRTH_DATE</code>.
     */
    public void setVbirthDate(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>STUDENT_HISTORY_VW.VBIRTH_DATE</code>.
     */
    public String getVbirthDate() {
        return (String) get(2);
    }

    /**
     * Setter for <code>STUDENT_HISTORY_VW.VDISTNO</code>.
     */
    public void setVdistno(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>STUDENT_HISTORY_VW.VDISTNO</code>.
     */
    public String getVdistno() {
        return (String) get(3);
    }

    /**
     * Setter for <code>STUDENT_HISTORY_VW.VENROLLED_GRADE_CODE</code>.
     */
    public void setVenrolledGradeCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>STUDENT_HISTORY_VW.VENROLLED_GRADE_CODE</code>.
     */
    public String getVenrolledGradeCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>STUDENT_HISTORY_VW.VLEGAL_GIVEN_NAME</code>.
     */
    public void setVlegalGivenName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>STUDENT_HISTORY_VW.VLEGAL_GIVEN_NAME</code>.
     */
    public String getVlegalGivenName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>STUDENT_HISTORY_VW.VLEGAL_MIDDLE_NAME</code>.
     */
    public void setVlegalMiddleName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>STUDENT_HISTORY_VW.VLEGAL_MIDDLE_NAME</code>.
     */
    public String getVlegalMiddleName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>STUDENT_HISTORY_VW.VLEGAL_SURNAME</code>.
     */
    public void setVlegalSurname(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>STUDENT_HISTORY_VW.VLEGAL_SURNAME</code>.
     */
    public String getVlegalSurname() {
        return (String) get(7);
    }

    /**
     * Setter for <code>STUDENT_HISTORY_VW.VPEN</code>.
     */
    public void setVpen(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>STUDENT_HISTORY_VW.VPEN</code>.
     */
    public String getVpen() {
        return (String) get(8);
    }

    /**
     * Setter for <code>STUDENT_HISTORY_VW.VPOSTAL</code>.
     */
    public void setVpostal(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>STUDENT_HISTORY_VW.VPOSTAL</code>.
     */
    public String getVpostal() {
        return (String) get(9);
    }

    /**
     * Setter for <code>STUDENT_HISTORY_VW.VSCHLNO</code>.
     */
    public void setVschlno(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>STUDENT_HISTORY_VW.VSCHLNO</code>.
     */
    public String getVschlno() {
        return (String) get(10);
    }

    /**
     * Setter for <code>STUDENT_HISTORY_VW.VSEX</code>.
     */
    public void setVsex(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>STUDENT_HISTORY_VW.VSEX</code>.
     */
    public String getVsex() {
        return (String) get(11);
    }

    /**
     * Setter for <code>STUDENT_HISTORY_VW.VSOURCE</code>.
     */
    public void setVsource(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>STUDENT_HISTORY_VW.VSOURCE</code>.
     */
    public String getVsource() {
        return (String) get(12);
    }

    /**
     * Setter for <code>STUDENT_HISTORY_VW.VUSUAL_GIVEN_NAME</code>.
     */
    public void setVusualGivenName(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>STUDENT_HISTORY_VW.VUSUAL_GIVEN_NAME</code>.
     */
    public String getVusualGivenName() {
        return (String) get(13);
    }

    /**
     * Setter for <code>STUDENT_HISTORY_VW.VUSUAL_MIDDLE_NAME</code>.
     */
    public void setVusualMiddleName(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>STUDENT_HISTORY_VW.VUSUAL_MIDDLE_NAME</code>.
     */
    public String getVusualMiddleName() {
        return (String) get(14);
    }

    /**
     * Setter for <code>STUDENT_HISTORY_VW.VUSUAL_SURNAME</code>.
     */
    public void setVusualSurname(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>STUDENT_HISTORY_VW.VUSUAL_SURNAME</code>.
     */
    public String getVusualSurname() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row16<String, Long, String, String, String, String, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    public Row16<String, Long, String, String, String, String, String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return StudentHistoryVw.STUDENT_HISTORY_VW.VLOCAL_STUDENT_ID;
    }

    @Override
    public Field<Long> field2() {
        return StudentHistoryVw.STUDENT_HISTORY_VW.VREPORT_DATE;
    }

    @Override
    public Field<String> field3() {
        return StudentHistoryVw.STUDENT_HISTORY_VW.VBIRTH_DATE;
    }

    @Override
    public Field<String> field4() {
        return StudentHistoryVw.STUDENT_HISTORY_VW.VDISTNO;
    }

    @Override
    public Field<String> field5() {
        return StudentHistoryVw.STUDENT_HISTORY_VW.VENROLLED_GRADE_CODE;
    }

    @Override
    public Field<String> field6() {
        return StudentHistoryVw.STUDENT_HISTORY_VW.VLEGAL_GIVEN_NAME;
    }

    @Override
    public Field<String> field7() {
        return StudentHistoryVw.STUDENT_HISTORY_VW.VLEGAL_MIDDLE_NAME;
    }

    @Override
    public Field<String> field8() {
        return StudentHistoryVw.STUDENT_HISTORY_VW.VLEGAL_SURNAME;
    }

    @Override
    public Field<String> field9() {
        return StudentHistoryVw.STUDENT_HISTORY_VW.VPEN;
    }

    @Override
    public Field<String> field10() {
        return StudentHistoryVw.STUDENT_HISTORY_VW.VPOSTAL;
    }

    @Override
    public Field<String> field11() {
        return StudentHistoryVw.STUDENT_HISTORY_VW.VSCHLNO;
    }

    @Override
    public Field<String> field12() {
        return StudentHistoryVw.STUDENT_HISTORY_VW.VSEX;
    }

    @Override
    public Field<String> field13() {
        return StudentHistoryVw.STUDENT_HISTORY_VW.VSOURCE;
    }

    @Override
    public Field<String> field14() {
        return StudentHistoryVw.STUDENT_HISTORY_VW.VUSUAL_GIVEN_NAME;
    }

    @Override
    public Field<String> field15() {
        return StudentHistoryVw.STUDENT_HISTORY_VW.VUSUAL_MIDDLE_NAME;
    }

    @Override
    public Field<String> field16() {
        return StudentHistoryVw.STUDENT_HISTORY_VW.VUSUAL_SURNAME;
    }

    @Override
    public String component1() {
        return getVlocalStudentId();
    }

    @Override
    public Long component2() {
        return getVreportDate();
    }

    @Override
    public String component3() {
        return getVbirthDate();
    }

    @Override
    public String component4() {
        return getVdistno();
    }

    @Override
    public String component5() {
        return getVenrolledGradeCode();
    }

    @Override
    public String component6() {
        return getVlegalGivenName();
    }

    @Override
    public String component7() {
        return getVlegalMiddleName();
    }

    @Override
    public String component8() {
        return getVlegalSurname();
    }

    @Override
    public String component9() {
        return getVpen();
    }

    @Override
    public String component10() {
        return getVpostal();
    }

    @Override
    public String component11() {
        return getVschlno();
    }

    @Override
    public String component12() {
        return getVsex();
    }

    @Override
    public String component13() {
        return getVsource();
    }

    @Override
    public String component14() {
        return getVusualGivenName();
    }

    @Override
    public String component15() {
        return getVusualMiddleName();
    }

    @Override
    public String component16() {
        return getVusualSurname();
    }

    @Override
    public String value1() {
        return getVlocalStudentId();
    }

    @Override
    public Long value2() {
        return getVreportDate();
    }

    @Override
    public String value3() {
        return getVbirthDate();
    }

    @Override
    public String value4() {
        return getVdistno();
    }

    @Override
    public String value5() {
        return getVenrolledGradeCode();
    }

    @Override
    public String value6() {
        return getVlegalGivenName();
    }

    @Override
    public String value7() {
        return getVlegalMiddleName();
    }

    @Override
    public String value8() {
        return getVlegalSurname();
    }

    @Override
    public String value9() {
        return getVpen();
    }

    @Override
    public String value10() {
        return getVpostal();
    }

    @Override
    public String value11() {
        return getVschlno();
    }

    @Override
    public String value12() {
        return getVsex();
    }

    @Override
    public String value13() {
        return getVsource();
    }

    @Override
    public String value14() {
        return getVusualGivenName();
    }

    @Override
    public String value15() {
        return getVusualMiddleName();
    }

    @Override
    public String value16() {
        return getVusualSurname();
    }

    @Override
    public StudentHistoryVwRecord value1(String value) {
        setVlocalStudentId(value);
        return this;
    }

    @Override
    public StudentHistoryVwRecord value2(Long value) {
        setVreportDate(value);
        return this;
    }

    @Override
    public StudentHistoryVwRecord value3(String value) {
        setVbirthDate(value);
        return this;
    }

    @Override
    public StudentHistoryVwRecord value4(String value) {
        setVdistno(value);
        return this;
    }

    @Override
    public StudentHistoryVwRecord value5(String value) {
        setVenrolledGradeCode(value);
        return this;
    }

    @Override
    public StudentHistoryVwRecord value6(String value) {
        setVlegalGivenName(value);
        return this;
    }

    @Override
    public StudentHistoryVwRecord value7(String value) {
        setVlegalMiddleName(value);
        return this;
    }

    @Override
    public StudentHistoryVwRecord value8(String value) {
        setVlegalSurname(value);
        return this;
    }

    @Override
    public StudentHistoryVwRecord value9(String value) {
        setVpen(value);
        return this;
    }

    @Override
    public StudentHistoryVwRecord value10(String value) {
        setVpostal(value);
        return this;
    }

    @Override
    public StudentHistoryVwRecord value11(String value) {
        setVschlno(value);
        return this;
    }

    @Override
    public StudentHistoryVwRecord value12(String value) {
        setVsex(value);
        return this;
    }

    @Override
    public StudentHistoryVwRecord value13(String value) {
        setVsource(value);
        return this;
    }

    @Override
    public StudentHistoryVwRecord value14(String value) {
        setVusualGivenName(value);
        return this;
    }

    @Override
    public StudentHistoryVwRecord value15(String value) {
        setVusualMiddleName(value);
        return this;
    }

    @Override
    public StudentHistoryVwRecord value16(String value) {
        setVusualSurname(value);
        return this;
    }

    @Override
    public StudentHistoryVwRecord values(String value1, Long value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15, String value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StudentHistoryVwRecord
     */
    public StudentHistoryVwRecord() {
        super(StudentHistoryVw.STUDENT_HISTORY_VW);
    }

    /**
     * Create a detached, initialised StudentHistoryVwRecord
     */
    public StudentHistoryVwRecord(String vlocalStudentId, Long vreportDate, String vbirthDate, String vdistno, String venrolledGradeCode, String vlegalGivenName, String vlegalMiddleName, String vlegalSurname, String vpen, String vpostal, String vschlno, String vsex, String vsource, String vusualGivenName, String vusualMiddleName, String vusualSurname) {
        super(StudentHistoryVw.STUDENT_HISTORY_VW);

        setVlocalStudentId(vlocalStudentId);
        setVreportDate(vreportDate);
        setVbirthDate(vbirthDate);
        setVdistno(vdistno);
        setVenrolledGradeCode(venrolledGradeCode);
        setVlegalGivenName(vlegalGivenName);
        setVlegalMiddleName(vlegalMiddleName);
        setVlegalSurname(vlegalSurname);
        setVpen(vpen);
        setVpostal(vpostal);
        setVschlno(vschlno);
        setVsex(vsex);
        setVsource(vsource);
        setVusualGivenName(vusualGivenName);
        setVusualMiddleName(vusualMiddleName);
        setVusualSurname(vusualSurname);
    }
}
