/*
 * This file is generated by jOOQ.
 */
package ca.bc.gov.educ.api.sld.jooq.tables.records;


import ca.bc.gov.educ.api.sld.jooq.tables.Student;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentRecord extends UpdatableRecordImpl<StudentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>STUDENT.REPORT_DATE</code>.
     */
    public void setReportDate(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>STUDENT.REPORT_DATE</code>.
     */
    public Long getReportDate() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>STUDENT.STUDENT_ID</code>.
     */
    public void setStudentId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>STUDENT.STUDENT_ID</code>.
     */
    public String getStudentId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>STUDENT.ADULT_GRAD</code>.
     */
    public void setAdultGrad(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>STUDENT.ADULT_GRAD</code>.
     */
    public String getAdultGrad() {
        return (String) get(2);
    }

    /**
     * Setter for <code>STUDENT.ADULT_TOTAL_CRS_HOURS</code>.
     */
    public void setAdultTotalCrsHours(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>STUDENT.ADULT_TOTAL_CRS_HOURS</code>.
     */
    public String getAdultTotalCrsHours() {
        return (String) get(3);
    }

    /**
     * Setter for <code>STUDENT.BAND_CODE</code>.
     */
    public void setBandCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>STUDENT.BAND_CODE</code>.
     */
    public String getBandCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>STUDENT.BIRTH_DATE</code>.
     */
    public void setBirthDate(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>STUDENT.BIRTH_DATE</code>.
     */
    public String getBirthDate() {
        return (String) get(5);
    }

    /**
     * Setter for <code>STUDENT.BIRTH_DAY</code>.
     */
    public void setBirthDay(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>STUDENT.BIRTH_DAY</code>.
     */
    public String getBirthDay() {
        return (String) get(6);
    }

    /**
     * Setter for <code>STUDENT.BIRTH_MONTH</code>.
     */
    public void setBirthMonth(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>STUDENT.BIRTH_MONTH</code>.
     */
    public String getBirthMonth() {
        return (String) get(7);
    }

    /**
     * Setter for <code>STUDENT.COLLEGE_COURSES</code>.
     */
    public void setCollegeCourses(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>STUDENT.COLLEGE_COURSES</code>.
     */
    public String getCollegeCourses() {
        return (String) get(8);
    }

    /**
     * Setter for <code>STUDENT.COUNTRY_CODE</code>.
     */
    public void setCountryCode(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>STUDENT.COUNTRY_CODE</code>.
     */
    public String getCountryCode() {
        return (String) get(9);
    }

    /**
     * Setter for <code>STUDENT.DISTNO</code>.
     */
    public void setDistno(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>STUDENT.DISTNO</code>.
     */
    public String getDistno() {
        return (String) get(10);
    }

    /**
     * Setter for <code>STUDENT.ENROLLED_GRADE_CODE</code>.
     */
    public void setEnrolledGradeCode(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>STUDENT.ENROLLED_GRADE_CODE</code>.
     */
    public String getEnrolledGradeCode() {
        return (String) get(11);
    }

    /**
     * Setter for <code>STUDENT.ESL_YRS</code>.
     */
    public void setEslYrs(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>STUDENT.ESL_YRS</code>.
     */
    public String getEslYrs() {
        return (String) get(12);
    }

    /**
     * Setter for <code>STUDENT.FUND_FEB_SPED</code>.
     */
    public void setFundFebSped(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>STUDENT.FUND_FEB_SPED</code>.
     */
    public String getFundFebSped() {
        return (String) get(13);
    }

    /**
     * Setter for <code>STUDENT.FY_ADJUST</code>.
     */
    public void setFyAdjust(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>STUDENT.FY_ADJUST</code>.
     */
    public String getFyAdjust() {
        return (String) get(14);
    }

    /**
     * Setter for <code>STUDENT.GRAD</code>.
     */
    public void setGrad(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>STUDENT.GRAD</code>.
     */
    public String getGrad() {
        return (String) get(15);
    }

    /**
     * Setter for <code>STUDENT.HOME_LANGUAGE_SPOKEN</code>.
     */
    public void setHomeLanguageSpoken(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>STUDENT.HOME_LANGUAGE_SPOKEN</code>.
     */
    public String getHomeLanguageSpoken() {
        return (String) get(16);
    }

    /**
     * Setter for <code>STUDENT.LEGAL_GIVEN_NAME</code>.
     */
    public void setLegalGivenName(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>STUDENT.LEGAL_GIVEN_NAME</code>.
     */
    public String getLegalGivenName() {
        return (String) get(17);
    }

    /**
     * Setter for <code>STUDENT.LEGAL_MIDDLE_NAME</code>.
     */
    public void setLegalMiddleName(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>STUDENT.LEGAL_MIDDLE_NAME</code>.
     */
    public String getLegalMiddleName() {
        return (String) get(18);
    }

    /**
     * Setter for <code>STUDENT.LEGAL_SURNAME</code>.
     */
    public void setLegalSurname(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>STUDENT.LEGAL_SURNAME</code>.
     */
    public String getLegalSurname() {
        return (String) get(19);
    }

    /**
     * Setter for <code>STUDENT.LOCAL_STUDENT_ID</code>.
     */
    public void setLocalStudentId(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>STUDENT.LOCAL_STUDENT_ID</code>.
     */
    public String getLocalStudentId() {
        return (String) get(20);
    }

    /**
     * Setter for <code>STUDENT.NATIVE_ANCESTRY_IND</code>.
     */
    public void setNativeAncestryInd(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>STUDENT.NATIVE_ANCESTRY_IND</code>.
     */
    public String getNativeAncestryInd() {
        return (String) get(21);
    }

    /**
     * Setter for <code>STUDENT.NOT_ELIG_FOR_PROV_FUNDING</code>.
     */
    public void setNotEligForProvFunding(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>STUDENT.NOT_ELIG_FOR_PROV_FUNDING</code>.
     */
    public String getNotEligForProvFunding() {
        return (String) get(22);
    }

    /**
     * Setter for <code>STUDENT.NUMBER_OF_COURSES</code>.
     */
    public void setNumberOfCourses(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>STUDENT.NUMBER_OF_COURSES</code>.
     */
    public String getNumberOfCourses() {
        return (String) get(23);
    }

    /**
     * Setter for <code>STUDENT.NUMBER_OF_SUPPORT_BLOCKS</code>.
     */
    public void setNumberOfSupportBlocks(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>STUDENT.NUMBER_OF_SUPPORT_BLOCKS</code>.
     */
    public String getNumberOfSupportBlocks() {
        return (String) get(24);
    }

    /**
     * Setter for <code>STUDENT.OTHER_COURSES</code>.
     */
    public void setOtherCourses(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>STUDENT.OTHER_COURSES</code>.
     */
    public String getOtherCourses() {
        return (String) get(25);
    }

    /**
     * Setter for <code>STUDENT.PEN</code>.
     */
    public void setPen(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>STUDENT.PEN</code>.
     */
    public String getPen() {
        return (String) get(26);
    }

    /**
     * Setter for <code>STUDENT.POSTAL</code>.
     */
    public void setPostal(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>STUDENT.POSTAL</code>.
     */
    public String getPostal() {
        return (String) get(27);
    }

    /**
     * Setter for <code>STUDENT.PROVINCE_CODE</code>.
     */
    public void setProvinceCode(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>STUDENT.PROVINCE_CODE</code>.
     */
    public String getProvinceCode() {
        return (String) get(28);
    }

    /**
     * Setter for <code>STUDENT.QUALIFIED_IS_STUDENT_IND</code>.
     */
    public void setQualifiedIsStudentInd(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>STUDENT.QUALIFIED_IS_STUDENT_IND</code>.
     */
    public String getQualifiedIsStudentInd() {
        return (String) get(29);
    }

    /**
     * Setter for <code>STUDENT.SCHLNO</code>.
     */
    public void setSchlno(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>STUDENT.SCHLNO</code>.
     */
    public String getSchlno() {
        return (String) get(30);
    }

    /**
     * Setter for <code>STUDENT.SCHOOL_FUNDING_CODE</code>.
     */
    public void setSchoolFundingCode(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>STUDENT.SCHOOL_FUNDING_CODE</code>.
     */
    public String getSchoolFundingCode() {
        return (String) get(31);
    }

    /**
     * Setter for <code>STUDENT.SEX</code>.
     */
    public void setSex(String value) {
        set(32, value);
    }

    /**
     * Getter for <code>STUDENT.SEX</code>.
     */
    public String getSex() {
        return (String) get(32);
    }

    /**
     * Setter for <code>STUDENT.SPED_CAT</code>.
     */
    public void setSpedCat(String value) {
        set(33, value);
    }

    /**
     * Getter for <code>STUDENT.SPED_CAT</code>.
     */
    public String getSpedCat() {
        return (String) get(33);
    }

    /**
     * Setter for <code>STUDENT.SPED_DESC2</code>.
     */
    public void setSpedDesc2(String value) {
        set(34, value);
    }

    /**
     * Getter for <code>STUDENT.SPED_DESC2</code>.
     */
    public String getSpedDesc2() {
        return (String) get(34);
    }

    /**
     * Setter for <code>STUDENT.STUDENT_FTE_VALUE</code>.
     */
    public void setStudentFteValue(String value) {
        set(35, value);
    }

    /**
     * Getter for <code>STUDENT.STUDENT_FTE_VALUE</code>.
     */
    public String getStudentFteValue() {
        return (String) get(35);
    }

    /**
     * Setter for <code>STUDENT.STUDENT_FUNDED_BY_CODE</code>.
     */
    public void setStudentFundedByCode(String value) {
        set(36, value);
    }

    /**
     * Getter for <code>STUDENT.STUDENT_FUNDED_BY_CODE</code>.
     */
    public String getStudentFundedByCode() {
        return (String) get(36);
    }

    /**
     * Setter for <code>STUDENT.USUAL_GIVEN_NAME</code>.
     */
    public void setUsualGivenName(String value) {
        set(37, value);
    }

    /**
     * Getter for <code>STUDENT.USUAL_GIVEN_NAME</code>.
     */
    public String getUsualGivenName() {
        return (String) get(37);
    }

    /**
     * Setter for <code>STUDENT.USUAL_MIDDLE_NAME</code>.
     */
    public void setUsualMiddleName(String value) {
        set(38, value);
    }

    /**
     * Getter for <code>STUDENT.USUAL_MIDDLE_NAME</code>.
     */
    public String getUsualMiddleName() {
        return (String) get(38);
    }

    /**
     * Setter for <code>STUDENT.USUAL_SURNAME</code>.
     */
    public void setUsualSurname(String value) {
        set(39, value);
    }

    /**
     * Getter for <code>STUDENT.USUAL_SURNAME</code>.
     */
    public String getUsualSurname() {
        return (String) get(39);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StudentRecord
     */
    public StudentRecord() {
        super(Student.STUDENT);
    }

    /**
     * Create a detached, initialised StudentRecord
     */
    public StudentRecord(Long reportDate, String studentId, String adultGrad, String adultTotalCrsHours, String bandCode, String birthDate, String birthDay, String birthMonth, String collegeCourses, String countryCode, String distno, String enrolledGradeCode, String eslYrs, String fundFebSped, String fyAdjust, String grad, String homeLanguageSpoken, String legalGivenName, String legalMiddleName, String legalSurname, String localStudentId, String nativeAncestryInd, String notEligForProvFunding, String numberOfCourses, String numberOfSupportBlocks, String otherCourses, String pen, String postal, String provinceCode, String qualifiedIsStudentInd, String schlno, String schoolFundingCode, String sex, String spedCat, String spedDesc2, String studentFteValue, String studentFundedByCode, String usualGivenName, String usualMiddleName, String usualSurname) {
        super(Student.STUDENT);

        setReportDate(reportDate);
        setStudentId(studentId);
        setAdultGrad(adultGrad);
        setAdultTotalCrsHours(adultTotalCrsHours);
        setBandCode(bandCode);
        setBirthDate(birthDate);
        setBirthDay(birthDay);
        setBirthMonth(birthMonth);
        setCollegeCourses(collegeCourses);
        setCountryCode(countryCode);
        setDistno(distno);
        setEnrolledGradeCode(enrolledGradeCode);
        setEslYrs(eslYrs);
        setFundFebSped(fundFebSped);
        setFyAdjust(fyAdjust);
        setGrad(grad);
        setHomeLanguageSpoken(homeLanguageSpoken);
        setLegalGivenName(legalGivenName);
        setLegalMiddleName(legalMiddleName);
        setLegalSurname(legalSurname);
        setLocalStudentId(localStudentId);
        setNativeAncestryInd(nativeAncestryInd);
        setNotEligForProvFunding(notEligForProvFunding);
        setNumberOfCourses(numberOfCourses);
        setNumberOfSupportBlocks(numberOfSupportBlocks);
        setOtherCourses(otherCourses);
        setPen(pen);
        setPostal(postal);
        setProvinceCode(provinceCode);
        setQualifiedIsStudentInd(qualifiedIsStudentInd);
        setSchlno(schlno);
        setSchoolFundingCode(schoolFundingCode);
        setSex(sex);
        setSpedCat(spedCat);
        setSpedDesc2(spedDesc2);
        setStudentFteValue(studentFteValue);
        setStudentFundedByCode(studentFundedByCode);
        setUsualGivenName(usualGivenName);
        setUsualMiddleName(usualMiddleName);
        setUsualSurname(usualSurname);
    }
}
