CREATE TABLE SLD_EVENT
(
    EVENT_ID      RAW(16)                             NOT NULL,
    EVENT_PAYLOAD BLOB                                NOT NULL,
    EVENT_STATUS  VARCHAR2(50)                        NOT NULL,
    EVENT_TYPE    VARCHAR2(100)                       NOT NULL,
    SAGA_ID       RAW(16),
    EVENT_OUTCOME VARCHAR2(100)                       NOT NULL,
    REPLY_CHANNEL VARCHAR2(100),
    CREATE_USER   VARCHAR(32)                         NOT NULL,
    CREATE_DATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER   VARCHAR(32)                         NOT NULL,
    UPDATE_DATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT SLD_EVENT_PK PRIMARY KEY (EVENT_ID)
) LOB (EVENT_PAYLOAD) STORE AS EVENT_PAYLOAD
(
    TABLESPACE API_PEN_BLOB_DATA
);
CREATE INDEX SLD_EVENT_STATUS_IDX ON SLD_EVENT (EVENT_STATUS) TABLESPACE API_PEN_IDX;
CREATE INDEX SLD_EVENT_SAGA_ID_IDX ON SLD_EVENT (SAGA_ID) TABLESPACE API_PEN_IDX;
CREATE INDEX SLD_EVENT_EVENT_TYPE_IDX ON SLD_EVENT (EVENT_TYPE) TABLESPACE API_PEN_IDX;
